-- Migration 000009: Clean up invalid URLs in gift_suggestions table
-- This migration removes or nullifies invalid URLs that were generated by AI

-- Remove URLs with fake Amazon product IDs
UPDATE gift_suggestions 
SET url = NULL 
WHERE url LIKE '%B07X9Y2ZYX%';

-- Remove URLs from fake/example domains
UPDATE gift_suggestions 
SET url = NULL 
WHERE url LIKE '%example.com%'
   OR url LIKE '%example.org%'
   OR url LIKE '%example.net%'
   OR url LIKE '%test.com%'
   OR url LIKE '%fake.com%'
   OR url LIKE '%dummy.com%';

-- Remove likely fake domains
UPDATE gift_suggestions 
SET url = NULL 
WHERE url LIKE '%gourmetcheese.com%'
   OR url LIKE '%winekit.com%';

-- Remove URLs that don't start with http:// or https://
UPDATE gift_suggestions 
SET url = NULL 
WHERE url IS NOT NULL 
  AND url != ''
  AND url NOT LIKE 'http://%'
  AND url NOT LIKE 'https://%';

-- Add a comment to track this cleanup
COMMENT ON COLUMN gift_suggestions.url IS 'Product URL - should be a real, valid URL or NULL. AI-generated suggestions should leave this field empty.';